import type { NextPage } from "next";
import Head from "next/head";
import { Jumbotron } from "../components/Jumbotron/Jumbotron";
import DefaultLayout from "../layouts/Default";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Cats World</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <DefaultLayout>
          <Jumbotron />
        </DefaultLayout>
      </main>
    </div>
  );
};

export default Home;
